### ISSUE TITLE
Better styling for inline code

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/borg#5]
Inline code is styled with a monospace font, but it's not obvious and can be hard to read:

![image](https://user-images.githubusercontent.com/2385329/68924856-5881bc00-078a-11ea-9818-ba3b204af885.png)

I'd like to suggest similar styling to what GitHub uses (e.g. a background colour and padding. Here's what it could look like:

![image](https://user-images.githubusercontent.com/2385329/68924973-a39bcf00-078a-11ea-944b-078fbe538e6b.png)

I just added the following CSS:

```css
code {
  background: #eee;
  padding: 0.2em 0.5em;
  border-radius: 3px;
}
```

Note that this makes code blocks (e.g. `<pre><code>...</code></pre>` look a bit weird as the first line is indented slightly. I think this can be fixed by also adding the following CSS:

```css
pre code {
  display: block;
  line-height: 1.5em;
}
```
